

[pathstr,~,~] = fileparts(mfilename('fullpath'));

oldpath = cd(pathstr);

addpath('lib')
addpath(fullfile(pathstr, 'lib', 'distributions'))
addpath(fullfile(pathstr, 'lib', 'distributions', 'Circle'))
addpath(fullfile(pathstr, 'lib', 'distributions', 'Hypersphere'))
addpath(fullfile(pathstr, 'lib', 'distributions', 'complexHypersphere'))
addpath(fullfile(pathstr, 'lib', 'distributions', 'Hypertorus'))
addpath(fullfile(pathstr, 'lib', 'distributions', 'Torus'))

addpath(fullfile(pathstr, 'lib', 'util'))
addpath(fullfile(pathstr, 'lib', 'util', 'autogenerated'))

cd(oldpath)
