function expression = cBinghamGradLogNorm2(in1)
%CBINGHAMGRADLOGNORM2
%    EXPRESSION = CBINGHAMGRADLOGNORM2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    21-Aug-2018 15:55:02

x1 = in1(1,:);
x2 = in1(2,:);
t2 = x1-x2;
t3 = 1.0./t2;
t4 = exp(x1);
t5 = t3.*t4;
t6 = exp(x2);
t7 = 1.0./t2.^2;
t10 = t3.*t6;
t8 = t5-t10;
t9 = 1.0./t8;
t11 = t6.*t7;
expression = [t9.*(t5+t11-t4.*t7),-t9.*(t10+t11-t4.*t7)];
