function expression = cBinghamGradLogNorm3(in1)
%CBINGHAMGRADLOGNORM3
%    EXPRESSION = CBINGHAMGRADLOGNORM3(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    21-Aug-2018 15:55:03

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
t2 = x1-x2;
t3 = 1.0./t2;
t4 = x1-x3;
t5 = 1.0./t4;
t6 = x2-x3;
t7 = 1.0./t6;
t8 = exp(x1);
t9 = t3.*t5.*t8;
t10 = exp(x2);
t11 = 1.0./t2.^2;
t12 = exp(x3);
t13 = 1.0./t4.^2;
t14 = t5.*t7.*t12;
t18 = t3.*t7.*t10;
t15 = t9+t14-t18;
t16 = 1.0./t15;
t17 = t5.*t8.*t11;
t19 = 1.0./t6.^2;
t20 = t3.*t8.*t13;
t21 = t5.*t12.*t19;
t22 = t7.*t12.*t13;
expression = [-t16.*(-t9+t17+t20+t22-t7.*t10.*t11),-t16.*(-t17+t18+t21+t7.*t10.*t11-t3.*t10.*t19),t16.*(t14+t20+t21+t22-t3.*t10.*t19)];
